apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - image: sameerhashmi/spring-music
        name: spring-music
        ports:
        - containerPort: 8080
